#!/usr/bin/env bash
# the script below will do the fizz buzz trick

for (( i=1; i<=100; i++ ))
do
	by_3=$((i % 3))
	by_5=$((i % 5))

	if [[ $by_3 == 0 && $by_5 == 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $by_3 == 0 ]]
	then
		echo "Fizz"
	elif [[ $by_5 == 0 ]]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done

