#!/usr/bin/env bash
# the script used while loop to print bad luck and good luck in specific locations

#initiate count variable
count=0

while [[ "$count" -lt 10 ]]
do
	if [[ "$count" -eq 3 ]]
	then
		echo "bad luck"
	elif [[ "$count" -eq 7 ]]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
