#!/usr/bin/env bash
#script to print superstitious numbers using while loop and case statement

#instantiate a count variable
count=1
while [[ "$count" -le 20 ]]
do
	case $count in
		4)
			echo -e "$count\nbad luck from China"
			;;
		9)
			echo -e "$count\nbad luck from Japan"
			;;
		17)
			echo -e "$count\nbad luck from Italy"
			;;
		*)
			echo "$count"
	esac
	((count++))
done
