#!/usr/bin/env bash
# This script demonstrates the use of nested while loop
i=0
while [[ i -le 12 ]]
do
	echo "Hour: $i"

		j=1		
		while [[ j -le 59 ]]
		do
			echo "$j"
			(( j++ ))
		done

	(( i++ ))
done
