#!/usr/bin/env bash
# this script will print display the content of the current directory in a list format
# Using a for loop to iterate over files in the current directory
for file in *
do
    # Check if the file is not a hidden file
    if [[ ! "$file" =~ ^\. ]]; then
        # Extract the part of the name after the first dash
        name_part=$(echo "$file" | cut -d'-' -f2-)
        echo "$name_part"
    fi
done

